/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INTERFACE;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JButton;

/**
 *
 * @author JordanaLeite
 */
public class JOGO extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JOGO.class.getName());
    
   JButton [][] btnCampos = new JButton[10][10];
   
   boolean [][] bombas = new boolean [10][10];
   boolean [][] abertos = new boolean [10][10];
   int quantidadeBombas = 15;
   boolean jogoEncerrado = false;
   
    
    public JOGO() {
        initComponents();
        criarTabuleiro();
        }
        
    public void criarTabuleiro (){
    
        painel_campo.setLayout(new GridLayout(10,10,2,2));
        
        for (int coluna = 0; coluna <= 9; coluna++){
        for (int linha = 0; linha <=9; linha++){
            JButton botao = new JButton();
            botao.setFont(new font("Times New Rowan", Font.BOLD, 14));
            botao.setBackground(new Color(51,102,0));
            botao.setForeground(Color.WHITE);
            
            botao.setFocusPainted(false);
            botao.setEnabled(false);
            
            btnCampos [linha][coluna] = botao;
            painel_campo.add(botao);
            
            
            
        }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        BTN_iniciar = new javax.swing.JButton();
        TF_tempo = new javax.swing.JTextField();
        painel_campo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(153, 0, 51));

        titulo.setBackground(new java.awt.Color(204, 255, 204));
        titulo.setFont(new java.awt.Font("Ravie", 3, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(51, 102, 0));
        titulo.setText("CAMPO MINADO DA DANOS MORAIS");

        BTN_iniciar.setBackground(new java.awt.Color(204, 255, 204));
        BTN_iniciar.setFont(new java.awt.Font("Ravie", 0, 20)); // NOI18N
        BTN_iniciar.setForeground(new java.awt.Color(51, 102, 0));
        BTN_iniciar.setText("INICIAR");

        TF_tempo.setEditable(false);
        TF_tempo.setBackground(new java.awt.Color(0, 0, 0));
        TF_tempo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TF_tempo.setForeground(new java.awt.Color(204, 0, 0));
        TF_tempo.setText("00:00");

        painel_campo.setBackground(new java.awt.Color(204, 255, 204));
        painel_campo.setForeground(new java.awt.Color(51, 102, 0));

        javax.swing.GroupLayout painel_campoLayout = new javax.swing.GroupLayout(painel_campo);
        painel_campo.setLayout(painel_campoLayout);
        painel_campoLayout.setHorizontalGroup(
            painel_campoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painel_campoLayout.setVerticalGroup(
            painel_campoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painel_campo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 563, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTN_iniciar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TF_tempo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_iniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel_campo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JOGO().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_iniciar;
    private javax.swing.JTextField TF_tempo;
    private javax.swing.JPanel painel_campo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
