/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package INTERFACE;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.Timer;


/**
 *
 * @author JordanaLeite
 */
public class JOGO extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JOGO.class.getName());
    
   JButton [][] btnCampos = new JButton[10][10];
   
   boolean [][] bombas = new boolean [10][10];
   boolean [][] abertos = new boolean [10][10];
   int quantidadeBombas = 15;
   int quantidadeCasasAbertas = 0;
   boolean jogoEncerrado = false;
   int segundosPassados = 0;
   Timer cronometro;
   
    
    public JOGO() {
        initComponents();
        criarTabuleiro();
        }
        
    public void criarTabuleiro (){
    
         // definir que o painel será dividido em 10 linhas e 10 clunas
   // com altura 2px e largura 2px
    painel_campo.setLayout(new GridLayout(10,10,2,2));
    
    for (int coluna=0;coluna<=9;coluna++){
     for(int linha=0;linha<=9;linha++){
    //VARIAVL BOTÃO PARA GUARDAR OS DADOS PROVISORIOS
    JButton botao= new JButton();
    botao.setFont(new Font("Arial", Font.BOLD,16));
    botao.setBackground(new Color(255,192,230));
    botao.setForeground(Color.WHITE);
    
    //remover marcas do botao q vem por padrao
    botao.setFocusPainted(false);
    botao.setEnabled(false);
    final int linhaSelecionada= linha;
                final int colunaSelecionada = coluna;
     botao.addActionListener((ActionEvent Evento)->{
                       abrirBotao(linhaSelecionada,colunaSelecionada); 
                
                            });
     //adicionar botão dentro da matriz
     btnCampos[linha][coluna]=botao;
     //adicionar dentro do painel
     painel_campo.add(botao);
        
    }
    }
    
    }  
    
    public void AdicionarBombas (){
      
        Random sorteador = new Random ();
        int bombasAdicionadas = 0;
        
        while (bombasAdicionadas < quantidadeBombas){
            int linha = sorteador.nextInt(10);
            int coluna = sorteador.nextInt(10);
            
            if (!bombas[linha][coluna]){
                bombas [linha][coluna] = true;
                bombasAdicionadas++;
            }

        }
       }

    public void IniciarJogo (){
        
        LimparJogo();

        AdicionarBombas ();
        IniciarCronometro();
        
      for (int coluna = 0; coluna  <=9; coluna++) {
          for (int linha = 0; linha <=9; linha++){
              JButton botao = btnCampos [linha] [coluna];
              botao.setEnabled(true);
              
          } // fim do 2° for
              
          } // fim do 1° for
      BTN_iniciar.setText("REINICIAR");
      } // fm do iniciar jogo
   
    public void abrirBotao(int linha, int coluna){
        // verificar se o jogo foi finalizado
        if(jogoEncerrado) return;
        
        //verificar se o botao ja foi aberto
        if(abertos[linha][coluna]) return;
      
        /*se o jogo ainda estiver rodando e o botão ainda não tiver
        sido aberto - então vamos abrir o botão*/
        abertos[linha][coluna]=true;
        quantidadeCasasAbertas++;
        
        // acessar o que tem dentro do botão
        JButton botao = btnCampos[linha][coluna];
        //se no botão tiver uma bomba, então vamos mostrar a bomba a ele
        if(bombas[linha][coluna]){
            //variavel que recebe nossa imagem
           ImageIcon imgBomba = new ImageIcon( 
                   getClass().getResource("/assets/bomba.png"));
           //colocar a imagem no botao
           botao.setIcon(imgBomba);
           FinalizarJogo (false);
           return;
        }else{
            ImageIcon imgBandeira = new ImageIcon(
            getClass().getResource("/assets/bandeira.png"));
            botao.setIcon(imgBandeira);
            return;
        }
        
    }// fim do metodo abrirBotao
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void FinalizarJogo (boolean venceu){
        // informar que o jogo acabou
        mostrarBombas ();
        jogoEncerrado = true;
        cronometro.stop();
        // verificar se a pessoa venceu ou não o jogo
        if (venceu) {
            JOptionPane.showMessageDialog(this, "Contrariando tudo e todos... você venceu!");
            LimparJogo();
        }else{
            JOptionPane.showMessageDialog(this, "De novo? É melhor abrir outro jogo...");
            LimparJogo();

        }
    }// fim do FinalizarJogo   
   
    public void VerificarVitoria (){
        // armazenar a quantidade de casas com bandeiras
        int casasSemBomba = 100 - quantidadeBombas;
        
        if (quantidadeCasasAbertas == casasSemBomba){
            FinalizarJogo (true);
        }
    }
    
    public void IniciarCronometro (){
        if (cronometro != null){
            cronometro.stop();
        }
        // reseta o cronometro
        segundosPassados = 0;
        TF_tempo.setText("00:00");
        
        cronometro = new Timer (1000, Evento->{
            segundosPassados++;
            int minutos = segundosPassados/60;
            int horas = minutos/60;
            int segundo = segundosPassados%60;
            TF_tempo.setText(
            String.format("%02d:%02d:%02d", horas, minutos, segundo)
            );
           
        });
         cronometro.start();
    }
    
    public void LimparJogo (){
        
        quantidadeCasasAbertas = 0;
        jogoEncerrado = false;
        IniciarCronometro ();
        
        for (int coluna = 0; coluna <= 9; coluna++){
            for (int linha = 0; linha <= 9; linha++){
                bombas [linha][coluna] = false;
                abertos [linha][coluna] = false;
                
                
                JButton botao = btnCampos [linha][coluna];
                botao.setIcon (null);
            }
        }
        AdicionarBombas();
        IniciarCronometro();
    }
  
    public void mostrarBombas (){
        
        for (int coluna = 0; coluna <= 9; coluna++){
            for (int linha = 0; linha <= 9; linha++){
            JButton botao = btnCampos [linha][coluna];
            if (bombas [linha][coluna]){
                ImageIcon imgBomba = new ImageIcon (
                getClass().getResource("/assets/bomba.png"));
                botao.setIcon (imgBomba);
            }
        }
        }
        
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        BTN_iniciar = new javax.swing.JButton();
        TF_tempo = new javax.swing.JTextField();
        painel_campo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(153, 0, 51));

        titulo.setBackground(new java.awt.Color(204, 255, 204));
        titulo.setFont(new java.awt.Font("Ravie", 3, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(51, 102, 0));
        titulo.setText("CAMPO MINADO DA DANOS MORAIS");

        BTN_iniciar.setBackground(new java.awt.Color(204, 255, 204));
        BTN_iniciar.setFont(new java.awt.Font("Ravie", 0, 20)); // NOI18N
        BTN_iniciar.setForeground(new java.awt.Color(51, 102, 0));
        BTN_iniciar.setText("INICIAR");
        BTN_iniciar.addActionListener(this::BTN_iniciarActionPerformed);

        TF_tempo.setEditable(false);
        TF_tempo.setBackground(new java.awt.Color(0, 0, 0));
        TF_tempo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TF_tempo.setForeground(new java.awt.Color(204, 0, 0));
        TF_tempo.setText("00:00");

        painel_campo.setBackground(new java.awt.Color(204, 255, 204));
        painel_campo.setForeground(new java.awt.Color(51, 102, 0));

        javax.swing.GroupLayout painel_campoLayout = new javax.swing.GroupLayout(painel_campo);
        painel_campo.setLayout(painel_campoLayout);
        painel_campoLayout.setHorizontalGroup(
            painel_campoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painel_campoLayout.setVerticalGroup(
            painel_campoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painel_campo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 563, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(TF_tempo))
                            .addComponent(BTN_iniciar))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_iniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painel_campo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_iniciarActionPerformed
        // TODO add your handling code here:
        IniciarJogo ();
        
    }//GEN-LAST:event_BTN_iniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JOGO().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_iniciar;
    private javax.swing.JTextField TF_tempo;
    private javax.swing.JPanel painel_campo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
